name: Build iOS Dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build Dylib
      run: |
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios_mc_client_dylib
        path: ios_mc_client.dylib
